title: "Kanwar Hamza"
baseurl: ""  # Leave empty!
url: "https://kanwarhamza.github.io"
theme: minima  # Default Jekyll theme
# Enable critical plugins
plugins:
  - jekyll-redirect-from

# Process these special folders
include:
  - _publications
  - _data
