name: Scholar Sync
on:
  workflow_dispatch:  # Manual trigger only (more reliable)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Manual Scholar Backup
        run: |
          cat > _data/scholar.yml << 'EOF'
          publications:
            - title: "Global stillbirths 1990–2021"
              authors: "GBD Collaborators (incl. Shuja KH)"
              year: "2024"
              venue: "The Lancet"
              url: "https://scholar.google.com/citations?view_op=view_citation&citation_for_view=ZfCrk2IAAAAJ:u-x6o8ySG0sC"
              doi: "10.1016/S0140-6736(24)01925-1"
          EOF
          
      - name: Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add _data/scholar.yml
          git commit -m "Manual scholar update [skip ci]" || exit 0
          git push
